# Default values for taskover.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: zoker/taskover 
  pullPolicy: IfNotPresent
  tag: "1.0.0"
  env:
    dbhost: "10.211.55.2"
    dbport: "3306"
    dbuser: "zoker"
    dbpasswd: "zoker"
    dbname: "taskover"
    secretkey: "SECRET_KEY_IN_HELM"
    static: "1"

service:
  type: NodePort 
  port: 3001
  nodePort: 30001
