apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskover.fullname" . }}
  labels:
    {{- include "taskover.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "taskover.selectorLabels" . | nindent 4 }}
