apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskover
spec:
  selector:
    matchLabels:
      purpose: taskover
  replicas: 3
  template:
    metadata:
      name: taskover
      labels:
        purpose: taskover
    spec:
      containers:
      - name: taskover
        image: zoker/taskover:1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_HOST
          value: "10.211.55.2"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          value: "zoker"
        - name: DATABASE_PASSWORD
          value: "zoker"
        - name: DATABASE_NAME
          value: "taskover"
        - name: SECRET_KEY_BASE
          value: "PODSECRET_KEY_BASE"
        - name: RAILS_SERVE_STATIC_FILES
          value: "1"
